# Site settings
title: Emmanuel 🎸 BOUSQUET
email: queta@club-internet.fr
url: https://emmanuelbousquet.fr/
description: "Professeur de guitare à Asnières-sur-Seine – Emmanuel Bousquet. Cours de guitare, piano, chant et solfège pour enfants, ados et adultes. Studio professionnel et pédagogie personnalisée."
keywords: "professeur de guitare Asnières-sur-Seine, cours de guitare enfants ados adultes, cours de piano Asnières-sur-Seine, cours de chant Asnières-sur-Seine, cours de solfège Hauts-de-Seine, apprendre guitare débutant avancé, professeur de musique Asnières, studio musique Asnières-sur-Seine, leçon de guitare individuelle, pédagogie musicale personnalisée"
#skills: "Web Developer - Graphic Artist - User Experience Designer"
skills: "Votre prof de guitare, piano et guitare basse </br> à ASNIÈRES-SUR-SEINE depuis 1980</br></br>
Des cours sur mesure, une méthode adaptée à chaque élève, et plus de 40 ans d’expérience pour vous guider, que vous soyez débutant ou avancé.</br></br>"
meta_author: Emmanuel Bousquet
web3forms_public_access_key: 6ec92076-fa0d-4f33-ae2f-369d77fe0ac3

phone: "06 27 09 12 83"
phone_hours: "09:00-20:00"
# Google webmaster tools
google_verify: google-site-verification=nMwPehO_g-DbbWZyuaDigDaVoOvsbhc44BwR3Ym5pOA

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 568C46 #568C46 #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Emmanuel BOUSQUET
  location: Adresse
  social: Sur le web
  contact: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: readme
    url: http://www.tablanote.com
  - title: youtube
    url: https://www.youtube.com/@tablanote7184

# Postal address (add as many lines as necessary)
address:
  - line: Rue Paul Gillet
  - line: 92600 Asnières-sur-Seine

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
